### ISSUE TITLE
What is the current status of automated installation of npm modules on hook.io?

### ISSUE THREAD

**Issue by SheetJSDev** [stackvana/hook.io#310]
Attempting to require the [`xlsx` module](https://www.npmjs.com/package/xlsx) results in the error `Cannot find module 'xlsx'`.  Based on [comments in the README](https://github.com/bigcompany/hook.io#why-or-how-would-i-want-to-use-hookio) and other issues, the service should automatically download and install modules that are not installed, but the [pending queue](http://hook.io/packages/npm/pending) does not refresh when a new module is required and the [error log](http://hook.io/packages/npm/error) is empty

**Comment by adifaidz** [comment]
I just had this too, wanted to require `easy-table` module but always results in error `Cannot find module 'easy-table'`. Checked the `Packages Pending Installation
` and `Packages which Erred on Installation` still to no  avail.
